export interface TarotCard {
  id: number;
  name: string;
  nameTR: string;
  arcana: "major" | "minor";
  suit?: "wands" | "cups" | "swords" | "pentacles";
  number: number | string;
  keywords: string[];
  keywordsTR: string[];
  upright: {
    meaning: string;
    meaningTR: string;
    love: string;
    career: string;
    spiritual: string;
  };
  reversed: {
    meaning: string;
    meaningTR: string;
  };
  symbolism: string;
  element?: string;
  planet?: string;
  zodiac?: string;
  imageUrl: string;
  color: string;
}

export const TAROT_CARDS: TarotCard[] = [
  // === BÜYÜK ARKANA ===
  {
    id: 0,
    name: "The Fool",
    nameTR: "Deli",
    arcana: "major",
    number: 0,
    keywords: ["beginnings", "innocence", "adventure", "freedom"],
    keywordsTR: ["yeni başlangıçlar", "masumiyet", "macera", "özgürlük"],
    upright: {
      meaning: "New beginnings, innocence, spontaneity, a free spirit",
      meaningTR: "Yeni başlangıçlar, masumiyet, kendiliğindenlik, özgür ruh — evren seni beklenmedik bir yolculuğa davet ediyor.",
      love: "Yeni bir aşkın kapısında duruyorsun. Kalbini açık tut.",
      career: "Cesaretli bir adım at. Risk almak gerekiyor.",
      spiritual: "Ruhun yeni bir yolculuğun başında. Her şeyi yeniden öğrenmeye hazır ol.",
    },
    reversed: {
      meaning: "Recklessness, risk-taking, inconsideration",
      meaningTR: "Düşüncesizlik, saf olmak, dikkatsizlik — adımlarını atmadan önce derin düşün.",
    },
    symbolism: "Uçurum kenarındaki genç figür sonsuz olasılıkları; beyaz gül saflığı; çanta birikmiş deneyimleri simgeler.",
    element: "Hava",
    planet: "Uranüs",
    imageUrl: "/cards/major/fool.svg",
    color: "#E8CC7A",
  },
  {
    id: 1,
    name: "The Magician",
    nameTR: "Büyücü",
    arcana: "major",
    number: 1,
    keywords: ["manifestation", "willpower", "skill", "concentration"],
    keywordsTR: ["tezahür", "irade gücü", "beceri", "odaklanma"],
    upright: {
      meaning: "Manifestation, resourcefulness, power, inspired action",
      meaningTR: "Elindeki tüm araçlara sahipsin. Yaratıcı güç sende — dilediğini gerçeğe dönüştürebilirsin.",
      love: "İlişkinde aktif ol. Hislerini eyleme döktür.",
      career: "Tüm yeteneklerin hazır. Projeyi başlatma zamanı.",
      spiritual: "Evrensel enerjiyi kanalladığını hissediyorsun. Bu gücü bilinçle kullan.",
    },
    reversed: {
      meaning: "Manipulation, poor planning, untapped talents",
      meaningTR: "Yeteneklerini manipülasyon için kullanıyorsun ya da gizlenmiş kapasitelerin var.",
    },
    symbolism: "Yukarı kaldırılan asa evrenle bağlantıyı; masa üzerindeki dört sembol dört elementi; sonsuzluk işareti sınırsız potansiyeli temsil eder.",
    element: "Hava",
    planet: "Merkür",
    imageUrl: "/cards/major/magician.svg",
    color: "#D4AF5F",
  },
  {
    id: 2,
    name: "The High Priestess",
    nameTR: "Yüksek Rahibe",
    arcana: "major",
    number: 2,
    keywords: ["intuition", "sacred knowledge", "divine feminine", "subconscious"],
    keywordsTR: ["sezgi", "kutsal bilgelik", "ilahi dişil", "bilinçdışı"],
    upright: {
      meaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind",
      meaningTR: "İç sesin sana rehberlik ediyor. Cevapları dışarıda değil, derinlerde ara. Sezgine güven.",
      love: "Söylenmeyene dikkat et. Karşındakinin sessizliğini oku.",
      career: "Acele etme. Doğru zamanı bekle, bilgelikle hareket et.",
      spiritual: "Mistik bilgiye kapın açılıyor. Meditasyon ve sessizlik rehberin olsun.",
    },
    reversed: {
      meaning: "Secrets, disconnected from intuition, withdrawal",
      meaningTR: "Sezginden kopuyorsun ya da sakladığın önemli sırlar var.",
    },
    symbolism: "İki sütun zıtlıkları; tul perdesi bilinmeyeni; hilal tacı dönüşümü simgeler.",
    element: "Su",
    planet: "Ay",
    imageUrl: "/cards/major/high-priestess.svg",
    color: "#8B75C6",
  },
  {
    id: 3,
    name: "The Empress",
    nameTR: "İmparatoriçe",
    arcana: "major",
    number: 3,
    keywords: ["femininity", "beauty", "nature", "abundance"],
    keywordsTR: ["dişil enerji", "güzellik", "doğa", "bolluk"],
    upright: {
      meaning: "Femininity, beauty, nature, nurturing, abundance",
      meaningTR: "Bereket ve yaratıcılık dönemindeysen. Kendinle ve doğayla uyum içinde olduğunda her şey filizleniyor.",
      love: "Sevgi verir, sevgi alırsın. İlişkini besle.",
      career: "Yaratıcı projeler için mükemmel zaman. Üretkenlik zirvede.",
      spiritual: "Doğayla bağlantı kur. Toprak altında ne filizlendiğini hisset.",
    },
    reversed: {
      meaning: "Creative block, dependence on others, smothering",
      meaningTR: "Yaratıcı blok ya da aşırı bağımlılık seni engelliyor.",
    },
    symbolism: "Altın başlık ve güzel giysi bolluğu; tahtta oturmak doğanın kraliçesini simgeler.",
    element: "Toprak",
    planet: "Venüs",
    imageUrl: "/cards/major/empress.svg",
    color: "#7A9E8A",
  },
  {
    id: 4,
    name: "The Emperor",
    nameTR: "İmparator",
    arcana: "major",
    number: 4,
    keywords: ["authority", "establishment", "structure", "father figure"],
    keywordsTR: ["otorite", "düzen", "yapı", "baba figürü"],
    upright: {
      meaning: "Authority, establishment, structure, a father figure",
      meaningTR: "Güçlü temeller üzerine inşa ediyorsun. Disiplin ve düzen, hayallerini gerçeğe dönüştürecek.",
      love: "İstikrar ve güvenilirlik ön planda. Uzun vadeli düşün.",
      career: "Liderlik pozisyonu için hazırsın. Yapıyı sen belirle.",
      spiritual: "Ruhsal pratiğine düzen getir. Disiplin, dönüşümün kapısı.",
    },
    reversed: {
      meaning: "Domination, excessive control, rigidity",
      meaningTR: "Aşırı kontrol ya da katılık seni kısıtlıyor.",
    },
    symbolism: "Taş tahtta oturmak otoriteyi; dört koç başı Koç burcunu simgeler.",
    element: "Ateş",
    zodiac: "Koç",
    imageUrl: "/cards/major/emperor.svg",
    color: "#C9818A",
  },
  {
    id: 5,
    name: "The Hierophant",
    nameTR: "Hiyerofant",
    arcana: "major",
    number: 5,
    keywords: ["tradition", "conformity", "morality", "education"],
    keywordsTR: ["gelenek", "uyum", "ahlak", "eğitim"],
    upright: {
      meaning: "Spiritual wisdom, religious beliefs, conformity, tradition, institutions",
      meaningTR: "Geleneksel bilgelik sana rehberlik ediyor. Bir mentor ya da öğreti hayatında önemli bir yere sahip.",
      love: "Geleneksel değerler ve taahhüt ön planda.",
      career: "Kurumsal yapılar içinde ilerle. Mentorlük ara.",
      spiritual: "Bir öğretinin ya da toplulığın içinde büyü.",
    },
    reversed: {
      meaning: "Personal beliefs, freedom, challenging the status quo",
      meaningTR: "Geleneklere meydan oku. Kendi spiritüel yolunu bul.",
    },
    symbolism: "Üçlü taç üç dünyayı; iki anahtar kutsal bilgiyi açar.",
    element: "Toprak",
    zodiac: "Boğa",
    imageUrl: "/cards/major/hierophant.svg",
    color: "#D4AF5F",
  },
  {
    id: 6,
    name: "The Lovers",
    nameTR: "Aşıklar",
    arcana: "major",
    number: 6,
    keywords: ["love", "harmony", "relationships", "values", "choices"],
    keywordsTR: ["aşk", "uyum", "ilişkiler", "değerler", "seçimler"],
    upright: {
      meaning: "Love, harmony, relationships, values alignment, choices",
      meaningTR: "Kalpten bir bağ ya da önemli bir seçim önünde duruyorsun. Değerlerin sana rehberlik edecek.",
      love: "Derin ve gerçek bir bağlantı. Ruhla ruhu buluşturan an.",
      career: "Tutkunu takip et. Sevdiğin işi seç.",
      spiritual: "Karşıtlıkları birleştiren aşk enerjisi içindeysin.",
    },
    reversed: {
      meaning: "Self-love, disharmony, imbalance, misaligned values",
      meaningTR: "Uyumsuzluk ya da yanlış seçimler. Kendi değerlerine dön.",
    },
    symbolism: "Melek üstte ilahi onayı; çıplak figürler saflığı simgeler.",
    element: "Hava",
    zodiac: "İkizler",
    imageUrl: "/cards/major/lovers.svg",
    color: "#E8CC7A",
  },
  {
    id: 7,
    name: "The Chariot",
    nameTR: "Savaş Arabası",
    arcana: "major",
    number: 7,
    keywords: ["control", "willpower", "success", "action", "determination"],
    keywordsTR: ["kontrol", "irade", "başarı", "eylem", "kararlılık"],
    upright: {
      meaning: "Control, willpower, success, action, determination",
      meaningTR: "Zafere giden yoldasın. Odağını koru ve iradenle engellerin üzerinden geç.",
      love: "Kazanmak için savaş, ama kalple. Dengeyi koru.",
      career: "Başarı yakın. Hedeften şaşma.",
      spiritual: "Içsel çatışmalarını kontrol altına al. Ruhun savaşçısı ol.",
    },
    reversed: {
      meaning: "Self-discipline, opposition, lack of direction",
      meaningTR: "Kontrolü kaybediyorsun. Yeniden odaklan.",
    },
    symbolism: "İki sfenks zıt güçleri; arabanın hareketsizliği içsel yolculuğu simgeler.",
    element: "Su",
    zodiac: "Yengeç",
    imageUrl: "/cards/major/chariot.svg",
    color: "#8B75C6",
  },
  {
    id: 8,
    name: "Strength",
    nameTR: "Güç",
    arcana: "major",
    number: 8,
    keywords: ["strength", "courage", "patience", "inner power"],
    keywordsTR: ["güç", "cesaret", "sabır", "iç güç"],
    upright: {
      meaning: "Strength, courage, patience, control, compassion",
      meaningTR: "Gerçek güç dışarıda değil, içinde. Sevgiyle, sabırla ve cesartle her engeli aşabilirsin.",
      love: "Yumuşak ama güçlü ol. Sevgin, korkudan değil güçten doğsun.",
      career: "Sabır ve öz disiplin seni zafere taşıyacak.",
      spiritual: "İçsel canavar seni değil, sen onu yönetiyorsun.",
    },
    reversed: {
      meaning: "Self doubt, weakness, insecurity",
      meaningTR: "İçsel korkular seni zayıflatıyor. Kendine güvenini yeniden bul.",
    },
    symbolism: "Aslanı ehlileştiren kadın hamuru sevgiyle; sonsuzluk işareti sınırsız gücü simgeler.",
    element: "Ateş",
    zodiac: "Aslan",
    imageUrl: "/cards/major/strength.svg",
    color: "#D4AF5F",
  },
  {
    id: 9,
    name: "The Hermit",
    nameTR: "Münzevi",
    arcana: "major",
    number: 9,
    keywords: ["soul-searching", "introspection", "solitude", "guidance"],
    keywordsTR: ["iç yolculuk", "içe dönüş", "yalnızlık", "rehberlik"],
    upright: {
      meaning: "Soul-searching, introspection, being alone, inner guidance",
      meaningTR: "Yalnızlık bir ceza değil, bir hediye. Bu sessizlikte bulacakların seni dönüştürecek.",
      love: "Önce kendini bul. Sonra başkasını.",
      career: "Dışarıdan gelen sesleri sustur. İçsel bilgeliğine danış.",
      spiritual: "Derin bir içe dönüş dönemindeysin. Işığı kendi içinde tut.",
    },
    reversed: {
      meaning: "Isolation, loneliness, withdrawal",
      meaningTR: "Aşırı izolasyon seni güçsüz kılıyor. Dışarıya çık.",
    },
    symbolism: "Fener içsel aydınlığı; dağ tepe zirvesini; asa deneyimi simgeler.",
    element: "Toprak",
    zodiac: "Başak",
    imageUrl: "/cards/major/hermit.svg",
    color: "#6B5BA6",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameTR: "Kader Çarkı",
    arcana: "major",
    number: 10,
    keywords: ["good luck", "karma", "life cycles", "destiny", "turning point"],
    keywordsTR: ["şans", "karma", "döngüler", "kader", "dönüm noktası"],
    upright: {
      meaning: "Good luck, karma, life cycles, destiny, a turning point",
      meaningTR: "Kader çarkı dönüyor ve rüzgar seninle. Değişimi kabul et — yeni bir döngü başlıyor.",
      love: "Beklenmedik bir dönüş. Kader el uzatıyor.",
      career: "Şanslı bir dönem. Fırsatları değerlendir.",
      spiritual: "Her şeyin bir döngüsü var. Şu an neredesin?",
    },
    reversed: {
      meaning: "Bad luck, resistance to change, breaking cycles",
      meaningTR: "Değişime direnç ya da döngüye kapılmışlık.",
    },
    symbolism: "Çark sonsuz döngüyü; TARO harfleri gizemi; köşelerdeki figürler dört elementi simgeler.",
    planet: "Jüpiter",
    imageUrl: "/cards/major/wheel.svg",
    color: "#E8CC7A",
  },
  {
    id: 11,
    name: "Justice",
    nameTR: "Adalet",
    arcana: "major",
    number: 11,
    keywords: ["justice", "fairness", "truth", "cause and effect", "law"],
    keywordsTR: ["adalet", "dürüstlük", "hakikat", "sebep sonuç", "denge"],
    upright: {
      meaning: "Justice, fairness, truth, cause and effect",
      meaningTR: "Her eylem bir sonuç doğurur. Hakikat ortaya çıkıyor — adalet, doğruyu teslim ediyor.",
      love: "Adil davran. Karşılıklı saygı temel.",
      career: "Sözleşmeler, kararlar ve dengeye dikkat et.",
      spiritual: "Karmik ders zamanı. Ne ektiysen onu biçiyorsun.",
    },
    reversed: {
      meaning: "Unfairness, dishonesty, lack of accountability",
      meaningTR: "Adaletsizlik veya hesap vermekten kaçınma.",
    },
    symbolism: "Kılıç hakikati; terazi dengeyi; kırmızı perde gizemi simgeler.",
    element: "Hava",
    zodiac: "Terazi",
    imageUrl: "/cards/major/justice.svg",
    color: "#C9818A",
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameTR: "Asılı Adam",
    arcana: "major",
    number: 12,
    keywords: ["pause", "surrender", "letting go", "new perspectives"],
    keywordsTR: ["duraklama", "teslim olma", "bırakma", "yeni bakış açısı"],
    upright: {
      meaning: "Pause, surrender, letting go, new perspectives",
      meaningTR: "Durmanın gücünü keşfediyorsun. Kontrolü bıraktığında hayat farklı görünüyor.",
      love: "Değişmeye izin ver. Beklentilerini bırak.",
      career: "Şimdi değil. Bekle ve izle.",
      spiritual: "Teslimiyette derin bir özgürlük var.",
    },
    reversed: {
      meaning: "Delays, resistance, stalling",
      meaningTR: "Aşırı fedakarlık ya da fırsatları kaçırma.",
    },
    symbolism: "Baş aşağı durmak farklı bakış açısını; altın ışık aydınlanmayı simgeler.",
    element: "Su",
    planet: "Neptün",
    imageUrl: "/cards/major/hanged-man.svg",
    color: "#8B75C6",
  },
  {
    id: 13,
    name: "Death",
    nameTR: "Ölüm",
    arcana: "major",
    number: 13,
    keywords: ["endings", "change", "transformation", "transition"],
    keywordsTR: ["sonlar", "değişim", "dönüşüm", "geçiş"],
    upright: {
      meaning: "Endings, change, transformation, transition",
      meaningTR: "Bir şey sona ermelidir ki yenisi doğsun. Dönüşüm kaçınılmaz — ve zorunlu.",
      love: "Eski kalıpları bırak. Yeni bir dönem başlıyor.",
      career: "Köklü değişim zamanı. Eskiyi bırakmaktan korkma.",
      spiritual: "Ego ölmeden ruh doğmaz.",
    },
    reversed: {
      meaning: "Resistance to change, personal transformation",
      meaningTR: "Değişime direnç. Bırakmaktan korkuyorsun.",
    },
    symbolism: "At siyah değil — dönüşümün rengi beyaz. Güneş ufkun ardında yeni başlangıçtır.",
    element: "Su",
    zodiac: "Akrep",
    imageUrl: "/cards/major/death.svg",
    color: "#4A2D8A",
  },
  {
    id: 14,
    name: "Temperance",
    nameTR: "Ilımlılık",
    arcana: "major",
    number: 14,
    keywords: ["balance", "moderation", "patience", "purpose"],
    keywordsTR: ["denge", "ılımlılık", "sabır", "amaç"],
    upright: {
      meaning: "Balance, moderation, patience, purpose",
      meaningTR: "Sabır ve denge seni yüceltiyor. Aşırılıklardan uzak dur. Ortada büyük bir güç var.",
      love: "Denge ve uyum. Aceleci olmadan büyüyen bir aşk.",
      career: "Sabırlı ol. Her şeyi zamanında yapıyorsun.",
      spiritual: "İki dünya arasında köprüsün. Ruh ve beden dengede.",
    },
    reversed: {
      meaning: "Imbalance, excess, self-healing needed",
      meaningTR: "Aşırılık ve dengesizlik. Kendini iyileştirmen gerekiyor.",
    },
    symbolism: "İki kap arasında akan su akışı; melek kanatları kutsal boyutu simgeler.",
    element: "Ateş",
    zodiac: "Yay",
    imageUrl: "/cards/major/temperance.svg",
    color: "#7A9E8A",
  },
  {
    id: 15,
    name: "The Devil",
    nameTR: "Şeytan",
    arcana: "major",
    number: 15,
    keywords: ["shadow self", "attachment", "addiction", "restriction"],
    keywordsTR: ["gölge benlik", "bağlılık", "bağımlılık", "kısıtlama"],
    upright: {
      meaning: "Shadow self, attachment, addiction, restriction, sexuality",
      meaningTR: "Neye zincirlendin? Seni tutan şey görünenden daha az güçlü. Zincirleri sen taktın, sen de çıkarabilirsin.",
      love: "Toksik bağlar ya da tutucu kıskançlık.",
      career: "Para ve güç tuzağı. Değerlerini yitirme.",
      spiritual: "Gölge benliğinle yüzleş. O sana ait.",
    },
    reversed: {
      meaning: "Releasing limiting beliefs, exploring dark thoughts, detachment",
      meaningTR: "Zincirlerden kurtuluş. Bağımlılıkları kırmak mümkün.",
    },
    symbolism: "Zincirler gönüllü bağlılığı; boynuzlar yıkıcı gücü simgeler.",
    element: "Toprak",
    zodiac: "Oğlak",
    imageUrl: "/cards/major/devil.svg",
    color: "#C9818A",
  },
  {
    id: 16,
    name: "The Tower",
    nameTR: "Kule",
    arcana: "major",
    number: 16,
    keywords: ["sudden change", "upheaval", "chaos", "revelation"],
    keywordsTR: ["ani değişim", "sarsılma", "kaos", "vahiy"],
    upright: {
      meaning: "Sudden change, upheaval, chaos, revelation, awakening",
      meaningTR: "Yıkılan her şey, kurulmaya değmeyenden arınıştır. Bu çöküşten sonra daha güçlü bir şey yükselecek.",
      love: "Beklenmedik bir kırılma. Temellerini sına.",
      career: "Ani değişim ya da kriz. Ama bu seni özgürleştirecek.",
      spiritual: "Kale yıkılmadan yeni bir tapınak inşa edilemez.",
    },
    reversed: {
      meaning: "Personal transformation, fear of change, averting disaster",
      meaningTR: "Felaketten kaçınma ya da kaçınılmaz değişimi geciktirme.",
    },
    symbolism: "Yıldırım ilahi müdahaleyi; düşen figürler eski benliği simgeler.",
    element: "Ateş",
    planet: "Mars",
    imageUrl: "/cards/major/tower.svg",
    color: "#C9818A",
  },
  {
    id: 17,
    name: "The Star",
    nameTR: "Yıldız",
    arcana: "major",
    number: 17,
    keywords: ["hope", "faith", "purpose", "renewal", "spirituality"],
    keywordsTR: ["umut", "inanç", "amaç", "yenilenme", "ruhsallık"],
    upright: {
      meaning: "Hope, faith, purpose, renewal, spirituality",
      meaningTR: "Karanlıktan sonra yıldızlar parlar. Umudun ışığını söndürme — evren seni görüyor.",
      love: "Şifa ve umut. Güzel bir şey geliyor.",
      career: "Uyumlu akış içindesin. İlham dolu dönem.",
      spiritual: "Evrenle uyum içindesin. Rehberlik alıyorsun.",
    },
    reversed: {
      meaning: "Lack of faith, despair, self-trust",
      meaningTR: "Umudu yitirmek. Kendine inanmayı bırakma.",
    },
    symbolism: "Sekiz köşeli yıldız uyumu; akan su bilinçdışından bilinçliye aktarımı simgeler.",
    element: "Hava",
    zodiac: "Kova",
    imageUrl: "/cards/major/star.svg",
    color: "#8B75C6",
  },
  {
    id: 18,
    name: "The Moon",
    nameTR: "Ay",
    arcana: "major",
    number: 18,
    keywords: ["illusion", "fear", "subconscious", "intuition", "dreams"],
    keywordsTR: ["yanılsama", "korku", "bilinçdışı", "sezgi", "rüyalar"],
    upright: {
      meaning: "Illusion, fear, the subconscious, intuition, dreams",
      meaningTR: "Her şey göründüğü gibi değil. Korku seni yanıltıyor olabilir. Sezgini ve rüyalarını dinle.",
      love: "Belirsizlik ve gizem. Gerçeği anlamaya çalış.",
      career: "Puslu dönem. Aceleci karar verme.",
      spiritual: "Bilinçdışın kapılarında duruyorsun. Rüyalarını kaydet.",
    },
    reversed: {
      meaning: "Release of fear, repressed emotion, inner confusion",
      meaningTR: "Korku ve illüzyondan kurtuluş. Netlik geliyor.",
    },
    symbolism: "İki kule yin-yang'ı; ıstakoz bilinçdışından yükselen korkuyu simgeler.",
    element: "Su",
    zodiac: "Balık",
    imageUrl: "/cards/major/moon.svg",
    color: "#4A2D8A",
  },
  {
    id: 19,
    name: "The Sun",
    nameTR: "Güneş",
    arcana: "major",
    number: 19,
    keywords: ["positivity", "fun", "warmth", "success", "vitality"],
    keywordsTR: ["olumlusulluk", "neşe", "sıcaklık", "başarı", "canlılık"],
    upright: {
      meaning: "Positivity, fun, warmth, success, vitality",
      meaningTR: "Her şey aydınlık. Bu dönemde ne dokunursan altın olur. Işığını dünyayla paylaş.",
      love: "Mutlu ve parlak bir aşk enerjisi.",
      career: "Başarı ve tanınma dönemi. Öne çık.",
      spiritual: "Ruhun parlamaya hazır. Işığını sakla.",
    },
    reversed: {
      meaning: "Inner child, feeling down, overly optimistic",
      meaningTR: "Geçici bir karamsarlık ya da aşırı iyimserlik.",
    },
    symbolism: "Güneş bilinç ve aydınlanmayı; çocuk masumiyeti ve neşeyi simgeler.",
    element: "Ateş",
    planet: "Güneş",
    imageUrl: "/cards/major/sun.svg",
    color: "#E8CC7A",
  },
  {
    id: 20,
    name: "Judgement",
    nameTR: "Yargı",
    arcana: "major",
    number: 20,
    keywords: ["reflection", "reckoning", "awakening", "absolution"],
    keywordsTR: ["yansıma", "hesaplaşma", "uyanış", "affetme"],
    upright: {
      meaning: "Judgement, reflection, reckoning, awakening",
      meaningTR: "Yeniden doğuş anı. Geçmişinle barış — bu uyanıştan sonra kim olacağını seç.",
      love: "Eski yaraları affet. Yeni bir başlangıç yap.",
      career: "Kritik değerlendirme zamanı. Vicdanını dinle.",
      spiritual: "Yüksek benliğin seni çağırıyor. Cevap ver.",
    },
    reversed: {
      meaning: "Self-doubt, inner critic, ignoring the call",
      meaningTR: "Çağrıyı görmezden geliyorsun. Özeleştiri seni felç ediyor.",
    },
    symbolism: "Borulu melek ilahi çağrıyı; yükselen figürler yeniden doğuşu simgeler.",
    element: "Ateş",
    planet: "Plüton",
    imageUrl: "/cards/major/judgement.svg",
    color: "#D4AF5F",
  },
  {
    id: 21,
    name: "The World",
    nameTR: "Dünya",
    arcana: "major",
    number: 21,
    keywords: ["completion", "integration", "accomplishment", "travel"],
    keywordsTR: ["tamamlanma", "bütünleşme", "başarı", "yolculuk"],
    upright: {
      meaning: "Completion, integration, accomplishment, travel",
      meaningTR: "Bir döngü tamamlandı. Başardın. Bu başarının tadını çıkar ve yeni bir spirale hazırlan.",
      love: "Tam ve mükemmel bir bütünlük hissi.",
      career: "Büyük bir projenin sonu. Zafer kazandın.",
      spiritual: "Evrenle tam bir uyum içindesin. Yeni bir yolculuğun arifesinde.",
    },
    reversed: {
      meaning: "Seeking personal closure, short-cuts",
      meaningTR: "Tamamlanmayan işler. Kısayollar seni hedeften uzaklaştırıyor.",
    },
    symbolism: "Çelenk tamamlanmayı; dört köşedeki figürler dört elementi simgeler.",
    element: "Toprak",
    planet: "Satürn",
    imageUrl: "/cards/major/world.svg",
    color: "#7A9E8A",
  },

  // === KÜÇÜK ARKANA — DEĞNEKLER (WANDS) ===
  {
    id: 22,
    name: "Ace of Wands",
    nameTR: "Değnekler Ası",
    arcana: "minor",
    suit: "wands",
    number: 1,
    keywords: ["inspiration", "new opportunities", "growth", "potential"],
    keywordsTR: ["ilham", "yeni fırsatlar", "büyüme", "potansiyel"],
    upright: {
      meaning: "Inspiration, new opportunities, growth, potential",
      meaningTR: "Yaratıcı bir ateş tutuşuyor içinde. Yeni bir projeye, tutkuya ya da yolculuğa başlamak için mükemmel an.",
      love: "Tutkulu yeni başlangıç.",
      career: "Girişimcilik ateşi yanıyor. Başla.",
      spiritual: "İlham seli. Bu enerjiyi somutlaştır.",
    },
    reversed: {
      meaning: "Delays, lack of motivation, weighed down",
      meaningTR: "Gecikme ve motivasyon kaybı. Ateşi yeniden tutuştur.",
    },
    symbolism: "Filizlenen değnek canlı potansiyeli simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/ace.svg",
    color: "#E8CC7A",
  },
  {
    id: 23,
    name: "Two of Wands",
    nameTR: "Değnekler İkilisi",
    arcana: "minor",
    suit: "wands",
    number: 2,
    keywords: ["planning", "future", "progress", "decisions"],
    keywordsTR: ["planlama", "gelecek", "ilerleme", "kararlar"],
    upright: {
      meaning: "Future planning, progress, decisions, discovery",
      meaningTR: "Ufukta büyük bir dünya var. Planlarını yap ve adım at.",
      love: "Geleceği birlikte planlamak.",
      career: "Büyük resme bak. Stratejini belirle.",
      spiritual: "Ruhun genişlemek istiyor.",
    },
    reversed: {
      meaning: "Fear of unknown, lack of planning",
      meaningTR: "Bilinmeyenden korku. Plan eksikliği.",
    },
    symbolism: "Küre dünyayı tutmak sonsuz olasılıkları simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/two.svg",
    color: "#D4AF5F",
  },
  {
    id: 24,
    name: "Three of Wands",
    nameTR: "Değnekler Üçlüsü",
    arcana: "minor",
    suit: "wands",
    number: 3,
    keywords: ["progress", "expansion", "foresight", "overseas"],
    keywordsTR: ["ilerleme", "genişleme", "öngörü", "yurtdışı"],
    upright: {
      meaning: "Progress, expansion, foresight, overseas opportunities",
      meaningTR: "Gemiler denize açıldı. Projeler ve planlar meyvelerini vermeye başlıyor.",
      love: "Uzun mesafeli bir ilişki ya da yeni bir boyut.",
      career: "Büyüme ve uluslararası fırsatlar.",
      spiritual: "Vizyonun gerçekleşiyor.",
    },
    reversed: {
      meaning: "Obstacles to long-term goals, delays in progress",
      meaningTR: "Engeller ve gecikmeler. Sabrın tükeniyor.",
    },
    symbolism: "Uzaklara bakan figür ufku ve geleceği simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/three.svg",
    color: "#C9818A",
  },
  {
    id: 25,
    name: "Four of Wands",
    nameTR: "Değnekler Dörtlüsü",
    arcana: "minor",
    suit: "wands",
    number: 4,
    keywords: ["celebration", "joy", "harmony", "relaxation", "homecoming"],
    keywordsTR: ["kutlama", "neşe", "uyum", "dinlenme", "eve dönüş"],
    upright: {
      meaning: "Celebration, joy, harmony, relaxation, homecoming",
      meaningTR: "Kutlama zamanı! Sevdiklerinle paylaş bu anı. Güzel bir temel attın.",
      love: "Nişan, düğün ya da birlikteliğin kutlaması.",
      career: "Bir başarıyı kutla. Ekibin seni destekliyor.",
      spiritual: "Topluluk ve ait olma hissi.",
    },
    reversed: {
      meaning: "Lack of support, transition, home conflict",
      meaningTR: "Ev ya da aile sorunları. Destek eksikliği.",
    },
    symbolism: "Dört değnek ve çiçek kemeri zaferi simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/four.svg",
    color: "#7A9E8A",
  },
  {
    id: 26,
    name: "Five of Wands",
    nameTR: "Değnekler Beşlisi",
    arcana: "minor",
    suit: "wands",
    number: 5,
    keywords: ["conflict", "competition", "diversity", "disagreement"],
    keywordsTR: ["çatışma", "rekabet", "çeşitlilik", "anlaşmazlık"],
    upright: {
      meaning: "Conflict, disagreements, competition, tension, diversity",
      meaningTR: "Çatışma ve rekabet kaçınılmaz. Ama bu sürtüşme seni güçlendiriyor.",
      love: "Anlaşmazlıklar ve gerginlik. Dinlemeyi öğren.",
      career: "Rekabetçi ortam. Kendini öne çıkar.",
      spiritual: "Farklı güçlerin çatışması içsel büyümeni tetikliyor.",
    },
    reversed: {
      meaning: "Inner conflict, conflict avoidance, tension release",
      meaningTR: "Çatışmadan kaçınma ya da çözüme yaklaşma.",
    },
    symbolism: "Beş kişinin değnek dövüşü kaotik rekabeti simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/five.svg",
    color: "#C9818A",
  },
  {
    id: 27,
    name: "Six of Wands",
    nameTR: "Değnekler Altılısı",
    arcana: "minor",
    suit: "wands",
    number: 6,
    keywords: ["success", "public recognition", "progress", "self-confidence"],
    keywordsTR: ["başarı", "tanınma", "ilerleme", "özgüven"],
    upright: {
      meaning: "Success, public recognition, progress, self-confidence",
      meaningTR: "Zafer alayında yürüyorsun. Başarın hak edilmiş — bunu kutla ve ilham ver.",
      love: "Güven ve tanınma. Sevginle öne çık.",
      career: "Terfi, ödül, tanınma geliyor.",
      spiritual: "Işığını göster. Dünya senin önderliğini bekliyor.",
    },
    reversed: {
      meaning: "Excess pride, lack of recognition, punishment",
      meaningTR: "Kibir ya da hak ettiğin tanınmayı görememe.",
    },
    symbolism: "Defne tacıyla at üzerindeki lider zaferi simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/six.svg",
    color: "#D4AF5F",
  },
  {
    id: 28,
    name: "Seven of Wands",
    nameTR: "Değnekler Yedilisi",
    arcana: "minor",
    suit: "wands",
    number: 7,
    keywords: ["challenge", "competition", "perseverance", "defensive"],
    keywordsTR: ["meydan okuma", "rekabet", "sebat", "savunma"],
    upright: {
      meaning: "Challenge, competition, perseverance, defensive",
      meaningTR: "Konumunu savun. Baskıya rağmen ayakta kal — bu direnç seni tanımlıyor.",
      love: "İlişkinde zorluklarla mücadele.",
      career: "Rekabete karşı dur. Konumunu koru.",
      spiritual: "İnançların saldırı altında. Sağlam dur.",
    },
    reversed: {
      meaning: "Exhaustion, giving up, overwhelmed",
      meaningTR: "Tükenme ve pes etmek istemek.",
    },
    symbolism: "Yüksekte savunma yapan figür direnci simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/seven.svg",
    color: "#8B75C6",
  },
  {
    id: 29,
    name: "Eight of Wands",
    nameTR: "Değnekler Sekizlisi",
    arcana: "minor",
    suit: "wands",
    number: 8,
    keywords: ["speed", "action", "air travel", "movement", "swift change"],
    keywordsTR: ["hız", "eylem", "haberleşme", "hareket", "ani değişim"],
    upright: {
      meaning: "Speed, action, air travel, movement, swift change",
      meaningTR: "Her şey hızla hareket ediyor. Akışa kapıl. Gecikme zamanı değil, eylem zamanı.",
      love: "Hızlı gelişmeler. Belirsizlik sona eriyor.",
      career: "Haberler, kararlar ve fırsatlar hızla geliyor.",
      spiritual: "Enerji akışta. Bu momentumu yakala.",
    },
    reversed: {
      meaning: "Delays, frustration, resisting change",
      meaningTR: "Gecikmeler ve engellenmiş enerji.",
    },
    symbolism: "Havada uçan sekiz değnek hız ve momentumu simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/eight.svg",
    color: "#E8CC7A",
  },
  {
    id: 30,
    name: "Nine of Wands",
    nameTR: "Değnekler Dokuzlusu",
    arcana: "minor",
    suit: "wands",
    number: 9,
    keywords: ["resilience", "courage", "persistence", "test of faith"],
    keywordsTR: ["dayanıklılık", "cesaret", "sebat", "inanç sınavı"],
    upright: {
      meaning: "Resilience, courage, persistence, test of faith, boundaries",
      meaningTR: "Neredeyse bitti. Son engel önünde dur — geçmişin sana gereken gücü verdi.",
      love: "Yaralı ama güçlü. Son adımı at.",
      career: "Engellere rağmen sebat et. Sonuna çok az kaldı.",
      spiritual: "Bu son sınav ruhunu temizliyor.",
    },
    reversed: {
      meaning: "Exhaustion, fatigue, questioning motivations",
      meaningTR: "Tükenme. Devam edebilir misin?",
    },
    symbolism: "Yaralı ama ayakta duran figür dayanıklılığı simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/nine.svg",
    color: "#7A9E8A",
  },
  {
    id: 31,
    name: "Ten of Wands",
    nameTR: "Değnekler Onlusu",
    arcana: "minor",
    suit: "wands",
    number: 10,
    keywords: ["burden", "extra responsibility", "hard work", "completion"],
    keywordsTR: ["yük", "sorumluluk", "sıkı çalışma", "tamamlanma"],
    upright: {
      meaning: "Burden, extra responsibility, hard work, completion",
      meaningTR: "Ağır bir yük taşıyorsun. Paylaşmayı öğren ya da bırakmayı.",
      love: "İlişki yük haline geliyor. Paylaşın.",
      career: "Aşırı iş yükü. Delege et.",
      spiritual: "Ne kadar ağırlık taşımak zorunda değilsin?",
    },
    reversed: {
      meaning: "Doing it all yourself, carrying the burden",
      meaningTR: "Yükü bırakmak ya da yardım kabul etmek.",
    },
    symbolism: "Değneklerle eğilen figür aşırı yüklenmişliği simgeler.",
    element: "Ateş",
    imageUrl: "/cards/wands/ten.svg",
    color: "#C9818A",
  },

  // === KÜÇÜK ARKANA — KUPALAR (CUPS) ===
  {
    id: 32,
    name: "Ace of Cups",
    nameTR: "Kupalar Ası",
    arcana: "minor",
    suit: "cups",
    number: 1,
    keywords: ["new feelings", "intuition", "intimacy", "love"],
    keywordsTR: ["yeni duygular", "sezgi", "yakınlık", "aşk"],
    upright: {
      meaning: "New feelings, intuition, intimacy, love, compassion",
      meaningTR: "Bir duygu doluyor taşıyor. Kalbin açık. Yeni bir sevgi ya da şifa dönemi başlıyor.",
      love: "Yeni bir aşkın doğuşu ya da derin bir yenilenme.",
      career: "Kalple yapılan iş. Yaratıcılık ve empati.",
      spiritual: "İlahi sevgi akıyor sana doğru.",
    },
    reversed: {
      meaning: "Emotional loss, blocked creativity, emptiness",
      meaningTR: "Tıkanmış duygular. Kalbin kapılarını aç.",
    },
    symbolism: "Taşan kupa sonsuz duygusal bolluğu simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/ace.svg",
    color: "#8B75C6",
  },
  {
    id: 33,
    name: "Two of Cups",
    nameTR: "Kupalar İkilisi",
    arcana: "minor",
    suit: "cups",
    number: 2,
    keywords: ["unity", "partnership", "mutual attraction", "relationships"],
    keywordsTR: ["birlik", "ortaklık", "karşılıklı çekim", "ilişki"],
    upright: {
      meaning: "Unity, partnership, mutual attraction, relationships, connection",
      meaningTR: "İki ruh buluşuyor. Karşılıklı saygı ve sevgiye dayanan güçlü bir bağ.",
      love: "Derin karşılıklı çekim. Ruh eşi enerjisi.",
      career: "Güçlü bir iş ortaklığı.",
      spiritual: "İki enerji uyum içinde dans ediyor.",
    },
    reversed: {
      meaning: "Self-love, break-ups, disharmony",
      meaningTR: "Uyumsuzluk ya da ayrılık.",
    },
    symbolism: "Kadeh alışverişi ve yılan sembolü denge ile şifayı simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/two.svg",
    color: "#C9818A",
  },
  {
    id: 34,
    name: "Three of Cups",
    nameTR: "Kupalar Üçlüsü",
    arcana: "minor",
    suit: "cups",
    number: 3,
    keywords: ["celebration", "friendship", "creativity", "community"],
    keywordsTR: ["kutlama", "arkadaşlık", "yaratıcılık", "topluluk"],
    upright: {
      meaning: "Celebration, friendship, creativity, collaborations",
      meaningTR: "Birlikte kutla! Sevdiklerinle olan anlar en değerli hazinedir.",
      love: "Sosyal çevre güçlü. Ortak kutlamalar.",
      career: "Takım başarısı ve kutlama.",
      spiritual: "Toplulukta büyüme ve şefkat.",
    },
    reversed: {
      meaning: "Gossip, overindulgence, isolation",
      meaningTR: "Dedikodu ve aşırılık. Gerçek dostluğu ara.",
    },
    symbolism: "Üç kadının kadeh kaldırması dostluğu ve kutlamayı simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/three.svg",
    color: "#7A9E8A",
  },
  {
    id: 35,
    name: "Four of Cups",
    nameTR: "Kupalar Dörtlüsü",
    arcana: "minor",
    suit: "cups",
    number: 4,
    keywords: ["contemplation", "apathy", "reevaluation", "disconnection"],
    keywordsTR: ["derin düşünce", "ilgisizlik", "yeniden değerlendirme", "kopukluk"],
    upright: {
      meaning: "Meditation, contemplation, apathy, reevaluation",
      meaningTR: "Sunulan fırsatları göremiyor musun? İçe dön — ne istediğini yeniden sorgula.",
      love: "Mevcut ilişkiye ilgisizlik.",
      career: "Mevcut durumdan memnunsuzluk.",
      spiritual: "Derin iç sorgulama. Yeni perspektif gerekiyor.",
    },
    reversed: {
      meaning: "Motivation, acceptance, choosing happiness",
      meaningTR: "Harekete geçme. Fırsatları gör.",
    },
    symbolism: "Meditasyondaki figür ve uzanan el görmezden gelinen fırsatı simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/four.svg",
    color: "#6B5BA6",
  },
  {
    id: 36,
    name: "Five of Cups",
    nameTR: "Kupalar Beşlisi",
    arcana: "minor",
    suit: "cups",
    number: 5,
    keywords: ["regret", "failure", "disappointment", "grief"],
    keywordsTR: ["pişmanlık", "başarısızlık", "hayal kırıklığı", "yas"],
    upright: {
      meaning: "Regret, failure, disappointment, pessimism",
      meaningTR: "Dökülen kuplara ağlıyorsun. Ama arkandaki iki kupa hâlâ dolu. Çevril.",
      love: "Hayal kırıklığı ve kayıp. Yasını tut ama ilerle.",
      career: "Başarısızlıktan ders al. Her şey bitmedi.",
      spiritual: "Yastaki ruh. Şifa zamanı.",
    },
    reversed: {
      meaning: "Personal setbacks, self-forgiveness, moving on",
      meaningTR: "İyileşme ve ilerleme. Geçmişi bırak.",
    },
    symbolism: "Üç dökülen kupa kaybı; iki dolu kupa umudu simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/five.svg",
    color: "#4A2D8A",
  },
  {
    id: 37,
    name: "Six of Cups",
    nameTR: "Kupalar Altılısı",
    arcana: "minor",
    suit: "cups",
    number: 6,
    keywords: ["nostalgia", "childhood memories", "innocence", "generosity"],
    keywordsTR: ["nostalji", "çocukluk", "masumiyet", "cömertlik"],
    upright: {
      meaning: "Nostalgia, childhood memories, innocence, generosity",
      meaningTR: "Geçmişten gelen bir güzellik şimdini besliyor. Masumiyet ve saf sevginin anısı.",
      love: "Eski bir aşk ya da masumane, saf bir bağ.",
      career: "Geçmişteki becerilerden yararlan.",
      spiritual: "İç çocuğunla buluş. Şifa buradan geliyor.",
    },
    reversed: {
      meaning: "Living in the past, naivety, forward movement",
      meaningTR: "Geçmişte takılı kalmak. İleriye bak.",
    },
    symbolism: "Çiçekli kupalar paylaşım ve çocukluk masumiyetini simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/six.svg",
    color: "#E8CC7A",
  },
  {
    id: 38,
    name: "Seven of Cups",
    nameTR: "Kupalar Yedilisi",
    arcana: "minor",
    suit: "cups",
    number: 7,
    keywords: ["choices", "fantasy", "illusion", "wishful thinking"],
    keywordsTR: ["seçimler", "fantezi", "illüzyon", "hayalcilik"],
    upright: {
      meaning: "Opportunities, choices, wishful thinking, illusion",
      meaningTR: "Pek çok hayal, çok az eylem. Hangi kupa gerçek, hangisi illüzyon? Odaklan.",
      love: "Çok fazla seçenek ya da gerçekçi olmayan beklentiler.",
      career: "Vizyonunu gerçeğe dönüştür. Hayal yetmez.",
      spiritual: "Gerçek ile illüzyonu ayırt et.",
    },
    reversed: {
      meaning: "Alignment, clarity, making choices",
      meaningTR: "Netlik kazanıyorsun. Gerçek yolunu seçiyorsun.",
    },
    symbolism: "Bulutlardaki farklı imgeli kupalar hayaller ve yanılsamaları simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/seven.svg",
    color: "#8B75C6",
  },
  {
    id: 39,
    name: "Eight of Cups",
    nameTR: "Kupalar Sekizlisi",
    arcana: "minor",
    suit: "cups",
    number: 8,
    keywords: ["disappointment", "abandonment", "withdrawal", "escapism"],
    keywordsTR: ["hayal kırıklığı", "terk etme", "çekilme", "kaçış"],
    upright: {
      meaning: "Disappointment, abandonment, withdrawal, escapism",
      meaningTR: "Yeterince değil. Daha derin bir şeyin peşinden git. Geride bırakmak cesaret ister.",
      love: "İlişkiyi bırakmak. Daha fazlasına layıksın.",
      career: "Tatminsiz kalan bir işi bırakmak.",
      spiritual: "Ruh daha derine çağırıyor. Cevap ver.",
    },
    reversed: {
      meaning: "Trying one more time, indecision, aimless drifting",
      meaningTR: "Geri dönmek mi yoksa ilerlemek mi?",
    },
    symbolism: "Gece ışığında ayrılan figür derin arayışı simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/eight.svg",
    color: "#6B5BA6",
  },
  {
    id: 40,
    name: "Nine of Cups",
    nameTR: "Kupalar Dokuzlusu",
    arcana: "minor",
    suit: "cups",
    number: 9,
    keywords: ["contentment", "satisfaction", "gratitude", "wishes"],
    keywordsTR: ["memnuniyet", "tatmin", "şükran", "dilekler"],
    upright: {
      meaning: "Contentment, satisfaction, gratitude, wishes fulfilled",
      meaningTR: "Dilek kartı! Gönül doygunluğunun zirvesindeysin. Şükran duy.",
      love: "Duygusal tatmin ve mutluluk.",
      career: "Başarı ve memnuniyet. Keyif al.",
      spiritual: "Evren sana armağanlar sunuyor.",
    },
    reversed: {
      meaning: "Inner happiness, materialism, dissatisfaction",
      meaningTR: "Dış tatmin yetmiyor. Derinlere in.",
    },
    symbolism: "Memnun figür ve dizili kupalar tatmin ve bolluğu simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/nine.svg",
    color: "#D4AF5F",
  },
  {
    id: 41,
    name: "Ten of Cups",
    nameTR: "Kupalar Onlusu",
    arcana: "minor",
    suit: "cups",
    number: 10,
    keywords: ["divine love", "harmony", "happiness", "family"],
    keywordsTR: ["ilahi aşk", "uyum", "mutluluk", "aile"],
    upright: {
      meaning: "Divine love, blissful relationships, harmony, alignment",
      meaningTR: "Mutluluğun zirvesi. Aile, sevgi ve uyum bir arada. Evrenle barışıksın.",
      love: "Sonsuz mutluluk. Mükemmel uyum.",
      career: "İş ve özel hayat dengesi. Huzur.",
      spiritual: "İlahi sevgiyle bütünleşme.",
    },
    reversed: {
      meaning: "Disconnection from family, unhappy home, conflict",
      meaningTR: "Aile uyumsuzluğu ya da hayal edilen mutluluğa ulaşamama.",
    },
    symbolism: "Gökkuşağı altında mutlu aile ilahi mutluluğu simgeler.",
    element: "Su",
    imageUrl: "/cards/cups/ten.svg",
    color: "#7A9E8A",
  },

  // === KÜÇÜK ARKANA — KILIÇLAR (SWORDS) ===
  {
    id: 42,
    name: "Ace of Swords",
    nameTR: "Kılıçlar Ası",
    arcana: "minor",
    suit: "swords",
    number: 1,
    keywords: ["breakthrough", "clarity", "sharp mind", "truth"],
    keywordsTR: ["atılım", "netlik", "keskin zihin", "hakikat"],
    upright: {
      meaning: "Breakthrough, clarity, sharp mind, truth, new idea",
      meaningTR: "Zihinsel bir netlik aydınlatıyor seni. Hakikati söyle, gerçeği gör, yeni bir fikir doğuyor.",
      love: "Dürüstlük ve açık iletişim.",
      career: "Yeni ve güçlü bir fikir. Uygula.",
      spiritual: "Hakikat kılıcı her illüzyonu kesiyor.",
    },
    reversed: {
      meaning: "Confusion, brutality, chaos",
      meaningTR: "Zihinsel karmaşa ve yanlış kullanılan güç.",
    },
    symbolism: "Taçlı kılıç zaferi; sis aşılmış engelleri simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/ace.svg",
    color: "#8B75C6",
  },
  {
    id: 43,
    name: "Two of Swords",
    nameTR: "Kılıçlar İkilisi",
    arcana: "minor",
    suit: "swords",
    number: 2,
    keywords: ["indecision", "choices", "stalemate", "blocked emotions"],
    keywordsTR: ["kararsızlık", "seçimler", "çıkmaz", "tıkanmış duygular"],
    upright: {
      meaning: "Difficult choices, indecision, stalemate",
      meaningTR: "İki yol önünde gözlerin bağlı bekliyorsun. Gözlerini aç — kalbine sor.",
      love: "Karar vermek istememe. Duyguları reddetme.",
      career: "İki seçenek arasında sıkışma.",
      spiritual: "Zihinsel blok. Meditasyonla içini dinle.",
    },
    reversed: {
      meaning: "Indecision, confusion, information overload",
      meaningTR: "Bilgi fazlası seni tıkıyor. Basitleştir.",
    },
    symbolism: "Gözleri bağlı figür ve çapraz kılıçlar çıkmazı simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/two.svg",
    color: "#6B5BA6",
  },
  {
    id: 44,
    name: "Three of Swords",
    nameTR: "Kılıçlar Üçlüsü",
    arcana: "minor",
    suit: "swords",
    number: 3,
    keywords: ["heartbreak", "suffering", "grief", "betrayal"],
    keywordsTR: ["kalp kırıklığı", "acı", "yas", "ihanet"],
    upright: {
      meaning: "Heartbreak, suffering, grief, rejection, separation",
      meaningTR: "Acı gerçek. Kalp kırıklığı kaçınılmaz bazen. Bu acı da geçer — ve seni daha derin yapar.",
      love: "İhanet ya da ayrılık acısı.",
      career: "Hayal kırıklığı ve red.",
      spiritual: "Kalp kırıklığı şefkati açar.",
    },
    reversed: {
      meaning: "Negative self-talk, releasing pain, optimism",
      meaningTR: "Acıdan çıkış. İyileşme başlıyor.",
    },
    symbolism: "Kalbe saplanmış üç kılıç gerçek acıyı simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/three.svg",
    color: "#C9818A",
  },
  {
    id: 45,
    name: "Four of Swords",
    nameTR: "Kılıçlar Dörtlüsü",
    arcana: "minor",
    suit: "swords",
    number: 4,
    keywords: ["rest", "restoration", "contemplation", "passivity"],
    keywordsTR: ["dinlenme", "iyileşme", "tefekkür", "pasiflik"],
    upright: {
      meaning: "Rest, restoration, contemplation, recuperation",
      meaningTR: "Dur. Dinlen. İyileşmek de bir eylemdir.",
      love: "İlişkiden zaman çek. Kendini topla.",
      career: "Mola ver. Yorgun zihin hata yapar.",
      spiritual: "Meditasyon ve sessizlik şifadır.",
    },
    reversed: {
      meaning: "Restlessness, burnout, lack of self-compassion",
      meaningTR: "Duramamak ya da tükenmişlik.",
    },
    symbolism: "Mezar benzeri dinleniş yeniden doğuşa hazırlanmayı simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/four.svg",
    color: "#4A2D8A",
  },
  {
    id: 46,
    name: "Five of Swords",
    nameTR: "Kılıçlar Beşlisi",
    arcana: "minor",
    suit: "swords",
    number: 5,
    keywords: ["conflict", "defeat", "winning at all costs", "betrayal"],
    keywordsTR: ["çatışma", "yenilgi", "her bedele kazanma", "ihanet"],
    upright: {
      meaning: "Unbridled ambition, win at all costs, sneakiness, conflict",
      meaningTR: "Her bedele kazanmak ne kadar değer? Bu zafer boş bir zafer olabilir.",
      love: "Güç çatışması. Ego ilişkiyi zehirliyor.",
      career: "Etik dışı rekabet. Dürüstlüğünü koru.",
      spiritual: "Gurur savaşı. Kim kazanır, kim kaybeder?",
    },
    reversed: {
      meaning: "Reconciliation, making amends, past wounds",
      meaningTR: "Barışma ve geçmişle yüzleşme.",
    },
    symbolism: "Kılıç toplayan figura yenik düşenler kaybı ve boş zaferi simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/five.svg",
    color: "#C9818A",
  },
  {
    id: 47,
    name: "Six of Swords",
    nameTR: "Kılıçlar Altılısı",
    arcana: "minor",
    suit: "swords",
    number: 6,
    keywords: ["transition", "change", "rite of passage", "moving on"],
    keywordsTR: ["geçiş", "değişim", "ritüel geçiş", "ilerleme"],
    upright: {
      meaning: "Transition, leaving behind, moving on, travel",
      meaningTR: "Huzurlu bir geçiş. Fırtınalı sulardan sakin sulara doğru kürek çekiyorsun.",
      love: "Zor bir dönemden çıkış. İyileşme yolculuğu.",
      career: "Mesleki geçiş ya da taşınma.",
      spiritual: "Eski bir yaşamı geride bırakarak ilerlemek.",
    },
    reversed: {
      meaning: "Personal transition, resistance to change, unfinished business",
      meaningTR: "Bitmemiş işler seni geride tutuyor.",
    },
    symbolism: "Teknedeki yolcular ve kılıçlar zor geçişi simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/six.svg",
    color: "#8B75C6",
  },
  {
    id: 48,
    name: "Seven of Swords",
    nameTR: "Kılıçlar Yedilisi",
    arcana: "minor",
    suit: "swords",
    number: 7,
    keywords: ["betrayal", "deception", "getting away with it", "strategy"],
    keywordsTR: ["ihanet", "hile", "kurnazlık", "strateji"],
    upright: {
      meaning: "Betrayal, deception, getting away with it, theft",
      meaningTR: "Birisi aldatıyor olabilir — ya çevrendeki biri ya da sen kendinle. Dürüstlüğü seç.",
      love: "Gizlilik ya da güvensizlik.",
      career: "Yanlış stratejiler ya da rakiplerin hilesi.",
      spiritual: "Kendinle dürüst ol. Gizli niyetler.",
    },
    reversed: {
      meaning: "Imposter syndrome, self-deceit, coming clean",
      meaningTR: "Gerçeği söyleme zamanı. İçsel dürüstlük.",
    },
    symbolism: "Kılıçları çalan figür kurnazlık ve kaçışı simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/seven.svg",
    color: "#6B5BA6",
  },
  {
    id: 49,
    name: "Eight of Swords",
    nameTR: "Kılıçlar Sekizlisi",
    arcana: "minor",
    suit: "swords",
    number: 8,
    keywords: ["negative thoughts", "self-imprisonment", "victim mentality"],
    keywordsTR: ["olumsuz düşünceler", "zihinsel hapis", "mağdur zihniyeti"],
    upright: {
      meaning: "Negative thoughts, self-imprisonment, victim mentality, restricted",
      meaningTR: "Zincirlerin çoğu zihinsel. Gözlerini aç — özgürlük düşündüğünden yakın.",
      love: "Korkudan gelen bağlılık.",
      career: "Sıkışmışlık hissi. Zihinsel engeller.",
      spiritual: "Zihin hapishanesi. Düşünceler gerçek değil.",
    },
    reversed: {
      meaning: "Self-acceptance, new perspective, freedom",
      meaningTR: "Serbest kalma. Zihinsel kısıtlamaların farkındasın.",
    },
    symbolism: "Bağlı ve gözleri kapalı figür zihinsel hapishaneyi simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/eight.svg",
    color: "#4A2D8A",
  },
  {
    id: 50,
    name: "Nine of Swords",
    nameTR: "Kılıçlar Dokuzlusu",
    arcana: "minor",
    suit: "swords",
    number: 9,
    keywords: ["anxiety", "worry", "fear", "depression", "nightmares"],
    keywordsTR: ["kaygı", "endişe", "korku", "depresyon", "kabuslar"],
    upright: {
      meaning: "Anxiety, worry, fear, depression, nightmares",
      meaningTR: "Gecenin karanlık saatleri. Endişeler seni uyutmuyor. Ama gece en uzun hissettirdiği anda biter.",
      love: "Kaygı ve endişe ilişkiyi gölgeliyor.",
      career: "Stres ve tükenmişlik.",
      spiritual: "Zihinsel acı. Şefkatle kendi kendine bak.",
    },
    reversed: {
      meaning: "Inner turmoil, deep-seated fears, secrets, mental health",
      meaningTR: "İyileşme. Korkularla yüzleşiyorsun.",
    },
    symbolism: "Geceleri ağlayan figür derin içsel acıyı simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/nine.svg",
    color: "#4A2D8A",
  },
  {
    id: 51,
    name: "Ten of Swords",
    nameTR: "Kılıçlar Onlusu",
    arcana: "minor",
    suit: "swords",
    number: 10,
    keywords: ["endings", "failure", "collapse", "backstabbing"],
    keywordsTR: ["sonlar", "çöküş", "ihanet", "hayal kırıklığı"],
    upright: {
      meaning: "Painful endings, deep wounds, betrayal, loss, crisis",
      meaningTR: "En dip nokta. Ama bundan daha aşağı inemezsin — tek yön yukarı. Şafak yakın.",
      love: "Ağrılı bir son. Kabul ve iyileşme.",
      career: "Büyük bir başarısızlık ya da ihanet.",
      spiritual: "Bu acı dönüştürücü. Diriliş bu noktadan gelir.",
    },
    reversed: {
      meaning: "Recovery, regeneration, resisting an inevitable end",
      meaningTR: "İyileşme ve yeniden doğuş. En kötü geride kaldı.",
    },
    symbolism: "On kılıç saplanmış yerde yatan figür tam çöküşü simgeler.",
    element: "Hava",
    imageUrl: "/cards/swords/ten.svg",
    color: "#C9818A",
  },

  // === KÜÇÜK ARKANA — PENTAKILLAR (PENTACLES) ===
  {
    id: 52,
    name: "Ace of Pentacles",
    nameTR: "Pentakıllar Ası",
    arcana: "minor",
    suit: "pentacles",
    number: 1,
    keywords: ["new financial opportunity", "manifestation", "abundance"],
    keywordsTR: ["yeni finansal fırsat", "tezahür", "bolluk"],
    upright: {
      meaning: "New financial or career opportunity, manifestation, abundance",
      meaningTR: "Maddi bir kapı açılıyor. Emeğin meyvelerini toplamaya hazır ol.",
      love: "Güvenli ve istikrarlı bir ilişki başlangıcı.",
      career: "Yeni bir iş veya gelir kaynağı.",
      spiritual: "Ruhsallık ve madde birleşiyor. Bereket çekmek.",
    },
    reversed: {
      meaning: "Lost opportunity, scarcity, lack of planning",
      meaningTR: "Kaçırılan fırsatlar ya da kötü finansal planlama.",
    },
    symbolism: "Altın pentakıl maddi dünyayı; filizlenen bahçe bereket kapısını simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/ace.svg",
    color: "#D4AF5F",
  },
  {
    id: 53,
    name: "Two of Pentacles",
    nameTR: "Pentakıllar İkilisi",
    arcana: "minor",
    suit: "pentacles",
    number: 2,
    keywords: ["balance", "adaptability", "time management", "juggling"],
    keywordsTR: ["denge", "uyum sağlama", "zaman yönetimi", "dengeleme"],
    upright: {
      meaning: "Balance, adaptability, time management, prioritization",
      meaningTR: "Çok şeyi dengeliyorsun. Esnekliğin gücün — ama sınırlarını bil.",
      love: "Zaman ve öncelik dengeleme.",
      career: "Birden fazla proje veya görev.",
      spiritual: "Yaşamın ritmi içinde dans et.",
    },
    reversed: {
      meaning: "Overwhelm, losing balance, financial disarray",
      meaningTR: "Denge kaybı. Önceliklerini yeniden belirle.",
    },
    symbolism: "Sonsuzluk işaretiyle iki pentakılı dengeleyen figür esnekliği simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/two.svg",
    color: "#7A9E8A",
  },
  {
    id: 54,
    name: "Three of Pentacles",
    nameTR: "Pentakıllar Üçlüsü",
    arcana: "minor",
    suit: "pentacles",
    number: 3,
    keywords: ["teamwork", "collaboration", "learning", "implementation"],
    keywordsTR: ["takım çalışması", "işbirliği", "öğrenme", "uygulama"],
    upright: {
      meaning: "Teamwork, collaboration, building, implementation",
      meaningTR: "Birlikte daha güçlüsünüz. Ortak bir projeye katkın değerli.",
      love: "Ortaklaşa inşa etme. Güçlü temel.",
      career: "Takım başarısı. Ustalaşma süreci.",
      spiritual: "Birlikte ruhsal büyüme.",
    },
    reversed: {
      meaning: "Lack of teamwork, disorganized, group conflict",
      meaningTR: "Takım uyumsuzluğu ya da işbirliği eksikliği.",
    },
    symbolism: "Katedralde çalışan üç kişi ustalaşma ve işbirliğini simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/three.svg",
    color: "#E8CC7A",
  },
  {
    id: 55,
    name: "Four of Pentacles",
    nameTR: "Pentakıllar Dörtlüsü",
    arcana: "minor",
    suit: "pentacles",
    number: 4,
    keywords: ["saving money", "security", "control", "conservatism"],
    keywordsTR: ["para biriktirme", "güvenlik", "kontrol", "tutuculuk"],
    upright: {
      meaning: "Saving money, security, control, conservatism",
      meaningTR: "Güvenlik istiyorsun — ama çok sıkı tutmak kaybettiriyor. Biraz bırak, biraz ver.",
      love: "Duygusal tutum ve bağlılık korkusu.",
      career: "Finansal güvenlik ama büyümeden kaçınma.",
      spiritual: "Bırakmak özgürleştiriyor.",
    },
    reversed: {
      meaning: "Over-spending, greed, self-protection",
      meaningTR: "Aşırı harcama ya da aşırı tutum.",
    },
    symbolism: "Pentakılları sıkıca tutan figür kontrolcü güvenliği simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/four.svg",
    color: "#C9818A",
  },
  {
    id: 56,
    name: "Five of Pentacles",
    nameTR: "Pentakıllar Beşlisi",
    arcana: "minor",
    suit: "pentacles",
    number: 5,
    keywords: ["financial loss", "poverty", "isolation", "hardship"],
    keywordsTR: ["finansal kayıp", "yoksulluk", "izolasyon", "zorluk"],
    upright: {
      meaning: "Financial loss, poverty, lack mindset, isolation, worry",
      meaningTR: "Zor zamanlardasın. Ama kilise penceresi ışıkla dolu — yardım kapıyı aramak gerekiyor.",
      love: "Yalnızlık ve izolasyon hissi.",
      career: "Finansal zorluk ya da iş kaybı.",
      spiritual: "Manevi fakriklik. Ruhsal destek ara.",
    },
    reversed: {
      meaning: "Recovery from financial loss, spiritual poverty",
      meaningTR: "İyileşme başlıyor. Destek alıyorsun.",
    },
    symbolism: "Karlı havada yürüyen iki figür ve parlak kilise penceresi umudu simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/five.svg",
    color: "#4A2D8A",
  },
  {
    id: 57,
    name: "Six of Pentacles",
    nameTR: "Pentakıllar Altılısı",
    arcana: "minor",
    suit: "pentacles",
    number: 6,
    keywords: ["giving", "receiving", "sharing", "generosity", "charity"],
    keywordsTR: ["verme", "alma", "paylaşma", "cömertlik", "yardım"],
    upright: {
      meaning: "Giving, receiving, sharing wealth, generosity, charity",
      meaningTR: "Bereket akıyor. Ver ve al — ikisi de kutsal. Denge sağlıksın.",
      love: "Dengeyi sev. Karşılıklı destek.",
      career: "Maddi bolluk ve paylaşma.",
      spiritual: "Vermek, almak kadar spiritüel.",
    },
    reversed: {
      meaning: "Strings-attached giving, power imbalance, debt",
      meaningTR: "Koşullu yardım ya da güç dengesizliği.",
    },
    symbolism: "Terazi tutan tüccar ve toprağa eğilen figürler dengeyi simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/six.svg",
    color: "#D4AF5F",
  },
  {
    id: 58,
    name: "Seven of Pentacles",
    nameTR: "Pentakıllar Yedilisi",
    arcana: "minor",
    suit: "pentacles",
    number: 7,
    keywords: ["long-term vision", "sustainable results", "patience", "investment"],
    keywordsTR: ["uzun vadeli vizyon", "sürdürülebilir sonuçlar", "sabır", "yatırım"],
    upright: {
      meaning: "Long-term vision, sustainable results, perseverance, investment",
      meaningTR: "Ektiklerini suluyorsun. Sonuçları görmek için sabır gerekiyor. Devam et.",
      love: "Uzun vadeli yatırım gerektiren bir ilişki.",
      career: "Uzun vadeli sonuçlar için sabret.",
      spiritual: "Spiritüel pratik meyve veriyor, yavaş yavaş.",
    },
    reversed: {
      meaning: "Lack of long-term vision, limited success or reward",
      meaningTR: "Sabırsızlık ya da sonuçsuz emek.",
    },
    symbolism: "Büyüyen bitkiyi izleyen çiftçi sabrı ve uzun vadeli yatırımı simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/seven.svg",
    color: "#7A9E8A",
  },
  {
    id: 59,
    name: "Eight of Pentacles",
    nameTR: "Pentakıllar Sekizlisi",
    arcana: "minor",
    suit: "pentacles",
    number: 8,
    keywords: ["apprenticeship", "education", "quality", "engagement"],
    keywordsTR: ["çıraklık", "eğitim", "kalite", "ustalık"],
    upright: {
      meaning: "Apprenticeship, repetitive tasks, mastery, skill development",
      meaningTR: "Ustalık sabır ve tekrar gerektirir. Her yaptığın iş seni mükemmelleştiriyor.",
      love: "İlişkiye emek vermek.",
      career: "Beceri geliştirme ve ustalaşma.",
      spiritual: "Spiritüel disiplin ve pratik.",
    },
    reversed: {
      meaning: "Self-development, perfectionism, misdirected activity",
      meaningTR: "Mükemmelliyetçilik ya da motivasyon eksikliği.",
    },
    symbolism: "Yıldız şeklinde pentakıllar yapan ustalık, özen ve ustalaşmayı simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/eight.svg",
    color: "#E8CC7A",
  },
  {
    id: 60,
    name: "Nine of Pentacles",
    nameTR: "Pentakıllar Dokuzlusu",
    arcana: "minor",
    suit: "pentacles",
    number: 9,
    keywords: ["abundance", "luxury", "self-reliance", "independence"],
    keywordsTR: ["bolluk", "lüks", "öz yetkinlik", "bağımsızlık"],
    upright: {
      meaning: "Abundance, luxury, self-reliance, financial independence",
      meaningTR: "Kendi çabalarınla yarattın bunu. Zenginliğini ve bağımsızlığını kutla.",
      love: "Bağımsız ve güçlü bir kadın/erkek enerjisi.",
      career: "Finansal bağımsızlık ve lüks.",
      spiritual: "Öz yeterliliğin meyvelerini topluyorsun.",
    },
    reversed: {
      meaning: "Self-worth, over-investment in work, hustling",
      meaningTR: "Maddi güvenliğe aşırı odaklanma.",
    },
    symbolism: "Bahçesinde zarif duran figür bağımsızlığı ve bolluğu simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/nine.svg",
    color: "#D4AF5F",
  },
  {
    id: 61,
    name: "Ten of Pentacles",
    nameTR: "Pentakıllar Onlusu",
    arcana: "minor",
    suit: "pentacles",
    number: 10,
    keywords: ["wealth", "financial security", "family", "long-term success"],
    keywordsTR: ["zenginlik", "finansal güvenlik", "aile", "uzun vadeli başarı"],
    upright: {
      meaning: "Wealth, financial security, family, long-term success, contribution",
      meaningTR: "Nesiller boyu sürecek bir bereket. Maddi ve manevi zenginlik tam uyumda.",
      love: "Güçlü ve güvenli bir aile bağı.",
      career: "Kalıcı başarı ve miras bırakma.",
      spiritual: "Maddi ve spiritüel bütünlük.",
    },
    reversed: {
      meaning: "Financial failure, loneliness, loss of family",
      meaningTR: "Finansal istikrarsızlık ya da aile sorunları.",
    },
    symbolism: "Aile sahnesindeki on pentakıl nesiller boyu zenginliği simgeler.",
    element: "Toprak",
    imageUrl: "/cards/pentacles/ten.svg",
    color: "#D4AF5F",
  },
];

export const MAJOR_ARCANA = TAROT_CARDS.filter(c => c.arcana === "major");
export const MINOR_ARCANA = TAROT_CARDS.filter(c => c.arcana === "minor");
export const WANDS = TAROT_CARDS.filter(c => c.suit === "wands");
export const CUPS = TAROT_CARDS.filter(c => c.suit === "cups");
export const SWORDS = TAROT_CARDS.filter(c => c.suit === "swords");
export const PENTACLES = TAROT_CARDS.filter(c => c.suit === "pentacles");

export function getCardById(id: number): TarotCard | undefined {
  return TAROT_CARDS.find(c => c.id === id);
}

export function getRandomCard(): TarotCard {
  return TAROT_CARDS[Math.floor(Math.random() * TAROT_CARDS.length)];
}

export function getRandomCards(count: number, excludeIds: number[] = []): TarotCard[] {
  const pool = TAROT_CARDS.filter(c => !excludeIds.includes(c.id));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getDailyCard(date: Date = new Date()): TarotCard {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000
  );
  const index = dayOfYear % TAROT_CARDS.length;
  return TAROT_CARDS[index];
}

export function calculateBirthCards(birthDate: Date): { primary: TarotCard; secondary?: TarotCard } {
  const day = birthDate.getDate();
  const month = birthDate.getMonth() + 1;
  const year = birthDate.getFullYear();

  let sum = day + month + year;
  while (sum > 22) {
    sum = String(sum).split("").reduce((a, b) => a + parseInt(b), 0);
  }

  const primaryId = sum === 22 ? 0 : sum - 1;
  const primary = MAJOR_ARCANA[primaryId] || MAJOR_ARCANA[0];

  let secondary: TarotCard | undefined;
  if (sum > 9) {
    const secSum = String(sum).split("").reduce((a, b) => a + parseInt(b), 0);
    if (secSum !== sum) {
      secondary = MAJOR_ARCANA[secSum - 1];
    }
  }

  return { primary, secondary };
}

export const MOON_PHASES = [
  { name: "Yeni Ay",       icon: "/icons/moon-new.png",            energy: "Yeni başlangıçlar, niyet belirleme", spreadSuggestion: "Yeni Ay Niyeti" },
  { name: "Hilal Ay",      icon: "/icons/moon-waxing-crescent.png",energy: "Büyüme, harekete geçme",             spreadSuggestion: "Büyüme Spread" },
  { name: "İlk Dördün",   icon: "/icons/moon-first-quarter.png",  energy: "Karar verme, eylem",                 spreadSuggestion: "Karar Spread" },
  { name: "Şişen Ay",     icon: "/icons/moon-waxing-gibbous.png", energy: "Geliştirme, ince ayar",              spreadSuggestion: "İlerleme Okuma" },
  { name: "Dolunay",       icon: "/icons/moon-full.png",           energy: "Tamamlanma, şükran, bırakma",        spreadSuggestion: "Dolunay Okuma" },
  { name: "Solan Ay",      icon: "/icons/moon-waning-gibbous.png", energy: "Şükran, paylaşma",                  spreadSuggestion: "Şükran Okuma" },
  { name: "Son Dördün",   icon: "/icons/moon-last-quarter.png",   energy: "Bırakma, temizlenme",                spreadSuggestion: "Bırakma Spread" },
  { name: "Eski Hilal",   icon: "/icons/moon-waning-crescent.png",energy: "Dinlenme, yansıma, sona erme",       spreadSuggestion: "Kapanış Okuma" },
];

export function getMoonPhase(date: Date = new Date()): typeof MOON_PHASES[0] {
  const known = new Date(2000, 0, 6);
  const msPerDay = 86400000;
  const daysSinceKnown = (date.getTime() - known.getTime()) / msPerDay;
  const lunarCycle = 29.53058867;
  const phase = ((daysSinceKnown % lunarCycle) / lunarCycle) * 8;
  return MOON_PHASES[Math.floor(phase) % 8];
}

export const SPREADS = [
  {
    id: "single",
    name: "Tek Kart",
    nameTR: "Günlük Rehber",
    description: "Günün enerjisini ortaya çıkaran tek bir mesaj.",
    cardCount: 1,
    positions: ["Mesaj"],
    icon: "/icons/spread-single.png",
    tier: "free",
  },
  {
    id: "three-card",
    name: "Three Card",
    nameTR: "Geçmiş · Şimdi · Gelecek",
    description: "Durumunun üç boyutunu açan klasik spread.",
    cardCount: 3,
    positions: ["Geçmiş", "Şimdi", "Gelecek"],
    icon: "/icons/spread-three.png",
    tier: "free",
  },
  {
    id: "love",
    name: "Love Reading",
    nameTR: "Aşk & İlişki",
    description: "İlişkinin dinamiklerini ve potansiyelini keşfeder.",
    cardCount: 5,
    positions: ["Sen", "Partner", "Bağ", "Engel", "Potansiyel"],
    icon: "/icons/spread-love.png",
    tier: "premium",
  },
  {
    id: "celtic-cross",
    name: "Celtic Cross",
    nameTR: "Kelt Haçı",
    description: "En kapsamlı 10 kartlık derinlemesine okuma.",
    cardCount: 10,
    positions: [
      "Mevcut Durum", "Zorluk", "Bilinçdışı Temel", "Geçmiş",
      "Olası Gelecek", "Yakın Gelecek", "Tutum", "Dış Etkiler",
      "Umut & Korku", "Sonuç"
    ],
    icon: "/icons/spread-celtic.png",
    tier: "premium",
  },
  {
    id: "shadow-work",
    name: "Shadow Work",
    nameTR: "Gölge Çalışması",
    description: "Gizlenen korkuları ve gölge benliği aydınlatır.",
    cardCount: 4,
    positions: ["Gölge", "Köken", "İfade", "Entegrasyon"],
    icon: "/icons/spread-shadow.png",
    tier: "premium",
  },
  {
    id: "year-ahead",
    name: "Year Ahead",
    nameTR: "Yıl Yolculuğu",
    description: "12 ay için spiritüel rehberlik sunan kapsamlı okuma.",
    cardCount: 12,
    positions: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
                "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    icon: "/icons/spread-year.png",
    tier: "premium",
  },
];
